repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-json
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: flake8
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        args: [--multi-line=3, --trailing-comma, --force-grid-wrap=0, --use-parentheses]


  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [--line-length=99]


  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.1.0
    hooks:
      - id: python-use-type-annotations

  - repo: https://github.com/pycqa/pydocstyle
    rev: 5.1.1  # pick a git hash / tag to point to
    hooks:
      - id: pydocstyle
        args:
          - --convention=google
        exclude: ^tests/


  - repo: https://github.com/dfm/black_nbconvert
    rev: stable
    hooks:
    - id: black_nbconvert

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.11.1
    hooks:
      - id: nbqa-black
        args: [--nbqa-mutate]
      - id: nbqa-isort
        args: [--nbqa-mutate]


  - repo: https://github.com/jazzband/pip-tools
    rev: 6.5.1
    hooks:
      - id: pip-compile
        name: pip-compile requirements.in
        files: ^requirements/requirements\.(in|txt)$
      - id: pip-compile
        name: pip-compile requirements-dev.in
        files: ^requirements/requirements_dev\.(in|txt)$
