sources:
  emt:
    credentials:
      email: myemail
      password: mypassword
      x_client_id: my_x_client_id
      passkey: my_passkey
    stops: [1,2]
    lines: [1,2]
  aemet:
    credentials:
      api_key: my_api_key
  

storage:
  default: local 
  config: 
    minio:
      access_key: my_access_key
      secret_key: my_secret_key
      endpoint: minio-endpoint
      secure: True
      bucket: my_bucket
    local:
      path: /path/to/save/datasets




