site_name: "INESDATA_MOV"
site_url: http://localhost
site_description: Data Generation
site_author: GMV

repo_url: https://github.com/oeg-upm/inesdata-mov-data-generation

theme:
  name: material
  locale: es
  highlightjs: true
  hljs_languages:
    - python
  features:
  - navigation.instant
  - content.code.copy

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


nav:
  - Home: index.md
